name: Generate Lambda List File

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  generate-lambda-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create Artifact Name
        id: artifact-name
        run: echo "ARTIFACT_NAME=artifact-PR${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Detect and list modified functions
        run: |
          git fetch origin main
          changed_dirs=$(git diff --name-only origin/main HEAD | grep '^lambdas/' | awk -F'/' '{print $2}' | uniq)
          echo "$changed_dirs" > ${{ env.ARTIFACT_NAME }}.txt
          cat ${{ env.ARTIFACT_NAME }}.txt

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::901195418002:role/GitHubAction-AssumeRoleWithAction
          role-session-name: Github-Pull-Request
          aws-region: us-west-2

      - name: Upload to S3
        run: |
          aws s3 cp ${{ env.ARTIFACT_NAME }}.txt s3://lambda-change-tracker
